import { createElement } from 'lwc';
import WireTest from 'c/wireTest';
import getAccountList from '@salesforce/apex/accountList.getAccList';

const mockResult=require('./data/accounts.json');

describe('c-wire-test', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-wire-test', {
            is: WireTest
        });
        document.body.appendChild(element);
        
        const elem=document.querySelector('c-wire-test');

        getAccountList.emit(mockResult);

       return Promise.resolve().then(()=>{

        const constant=elem.shadowRoot.querySelectorAll('p');
        expect(constant.length).toBe(mockResult.length);
        expect(constant[0].textContent).toBe(mockResult[0].Name);
    })
    });
});